### ISSUE TITLE
Document CSV config-file settings; explain why warning occurs about 'unsused LDAP connector'

### ISSUE THREAD

**Issue by raymond-ensemble** [adobe-apiplatform/user-sync.py#110]
**Steps**
1. Run the user-sync without any arguments (python user-sync.pex) or reading from a csv file only (python user-sync.pex --users file users-file.csv --process-groups)

**Results**
- There would be a warning message: "WARNING config - Found unused keys: ['ldap'] in: <user-sync-config.yml>.directory.connectors"

**Comment by ianmak** [comment]
not sure if this is actually a bug, but I asked Raymond to log this anyways just to discuss it

**Comment by adobeDan** [comment]
I don't actually think this is a bug.  If the config file is set up to use the ldap connector, and the user switches to csv input, I think that's an appropriate warning.  If they are using csv regularly, they should probably replace the ldap settings with csv settings (yes, we have those :).

I'm changing this to be a docs request, because we need to document the CSV settings and show that you can have them in your config file.

**Comment by adobeDan** [comment]
I fixed this in pull #139, although the commit says #4.  This should be closed when that PR is merged, because the docs have also been fixed up.
