### ISSUE TITLE
Unhandled Exception is shown when syncing users from csv file and having extended_attributes in config

### ISSUE THREAD

**Issue by raymond-ensemble** [adobe-apiplatform/user-sync.py#112]
**Steps**
1. Set up a custom attribute in the config:
> extensions:
>   - context: per-user
>     extended_attributes:
>       - sn
>     extended_dashboard_groups:
>       - Ensemble Test
>       - Ensemble Test 2
>     after_mapping_hook: |
>       sn = source_attributes.get('sn')
>       target_attributes['firstname'] = 'Ensemble123'
>       if int(sn) > 3:
>         target_groups.add('Ensemble Test')
>       elif int(sn) <= 3 :
>         target_groups.add('Ensemble Test 2')
2. Run the user-sync while pointing to a csv user file: **python user-sync.pex --users file users-file.csv**

**Results**
- This error would appear:
> 2017-03-24 15:10:06 6164 ERROR main - Unhandled exception
> Traceback (most recent call last):
>   File "c:\users\raymondf\.pex\install\user_sync-1.2rc2-py2-none-any.whl.f8ddbb45621af04445afc502d8a
> 9ef65e0bf86fb\user_sync-1.2rc2-py2-none-any.whl\user_sync\app.py", line 363, in main
>     begin_work(config_loader)
>   File "c:\users\raymondf\.pex\install\user_sync-1.2rc2-py2-none-any.whl.f8ddbb45621af04445afc502d8a
> 9ef65e0bf86fb\user_sync-1.2rc2-py2-none-any.whl\user_sync\app.py", line 209, in begin_work
>     rule_processor.run(directory_groups, directory_connector, dashboard_connectors)
>   File "c:\users\raymondf\.pex\install\user_sync-1.2rc2-py2-none-any.whl.f8ddbb45621af04445afc502d8a
> 9ef65e0bf86fb\user_sync-1.2rc2-py2-none-any.whl\user_sync\rules.py", line 157, in run
>     self.read_desired_user_groups(directory_groups, directory_connector)
>   File "c:\users\raymondf\.pex\install\user_sync-1.2rc2-py2-none-any.whl.f8ddbb45621af04445afc502d8a
> 9ef65e0bf86fb\user_sync-1.2rc2-py2-none-any.whl\user_sync\rules.py", line 291, in read_desired_user_
> groups
>     exec(options['after_mapping_hook'], self.after_mapping_hook_scope)
>   File "<per-user after-mapping-hook>", line 3, in <module>
> TypeError: int() argument must be a string or a number, not 'NoneType'
> 2017-03-24 15:10:06 6164 INFO main - ========== End Run (User Sync version: 1.2rc2) (Total time: 0:0
> 0:02)

**Comment by adobeDan** [comment]
@raymond-ensemble Can you please attach your user-sync-config.yml file in full, rather than just copying in the segment?  I want to make sure I can repro this.  Also can you post your log file and users file?

Note: if they contain sensitive data (like people's emails that you don't want public), feel free to email me the config file and log file and users file directly.  Thanks!

**Comment by adobeDan** [comment]
@raymond-ensemble By the way, at first glance what this looks like to me is that you have an empty sn field for one of your rows, and that comes in as a source attribute value of None.  Then on line 3 of your code you say `int(sn)` which becomes `int(None)` which gets you the error you are seeing.

The way you can tell this is in your extension code is that the bottom of the trace says 'File "", line 3, in' which means it was not in a source file or function (compare that last line with the lines above).

The canonical way of writing defensive code in your extensions is to always guard for None in your code, so for example change `int(sn)` to be `int(sn or 0)` which gives you a 0 if `sn` is None.

**Comment by raymond-ensemble** [comment]
I don't encounter this issue when I run it pointing to AD. I tried adding the custom attribute "sn" in the users-file, but I still get the error.

I've converted the files to .txt in order to upload it here.

[users-sync-config.txt](https://github.com/adobe-apiplatform/user-sync.py/files/869491/users-sync-config.txt)
[users-file.txt](https://github.com/adobe-apiplatform/user-sync.py/files/869505/users-file.txt)

**Comment by adobeDan** [comment]
You have a bug in your CSV file.  Here's your header row:
```
firstname,lastname,email,country,groups,type,user,domain,sn
```
and here's a sample row:
```
!CCE_win,001,ccewin1@ensemble.ca,CA,"CSV Multi Group 1,CSV Multi Group 2",enterpriseID,5
```
If you count the commas (i.e., the fields) going across your sample row, and match them with the column names in your header row, you get these column assignments:

* firstname = `!CCE_win`
* lastname = `001`
* email = `ccewin1@ensemble.ca`
* country = `CA`
* groups = `CSV Multi Group 1,CSV Multi Group 2`
* type = `enterpriseID`
* user = `5`
* domain = `None`
* sn = `None`

That gets you the exception you are seeing, because there is nothing in the `sn` column (as I explained in my comment above).

I understand that you don't have username and domain values for your enterpriseID users, so I suggest that you simply move the `sn` field earlier in your header (you can put it anywhere).  For example, if you just change your header line to be:
```
firstname,lastname,email,country,groups,type,sn,user,domain
```
then your columns will match what you have in your data and everything will work fine.

**Comment by raymond-ensemble** [comment]
Ah, I got it to work now. Thanks

**Comment by adobeDan** [comment]
OK, great, glad it's working for you!  I'll close the issue.
