### ISSUE TITLE
Can't execute user-sync.pex in Win10

### ISSUE THREAD

**Issue by StitchFurbix** [adobe-apiplatform/user-sync.py#120]
Hi gang,

I'm sorry but I can figure out why the pex file keeps failing to run. I've tried getting different versions of python and installing dependencies individually. 

Here's the error I keep getting from my various attempts:

H:\adobe\user-sync>py -2 user-sync.pex
Failed to execute PEX file, missing compatible dependencies for:
pyyaml
cryptography
pycrypto
cffi
umapi-client
psutil
user-sync
python-ldap

H:\adobe\user-sync>py user-sync.pex
Failed to execute PEX file, missing compatible dependencies for:
pyyaml
cryptography
pycrypto
cffi
umapi-client
psutil
user-sync
python-ldap

H:\adobe\user-sync>C:\Python27\python.exe user-sync.pex
Failed to execute PEX file, missing compatible dependencies for:
pyyaml
cryptography
pycrypto
cffi
umapi-client
psutil
user-sync
python-ldap

H:\adobe\user-sync>

**Comment by phil-levy** [comment]
Looks like you are running on Windows.  First, try the windows pathname length limit workaround.  It is in the documentation but to save time here is the relevant part:

In Windows only:

Before running the user-sync.pex executable in Windows, you might need to work around a Windows-only Python execution issue:

The Windows operating system enforces a file path length limit of 260 characters. When executing a Python PEX file, it creates a temporary location to extract the contents of the package. If the path to that location exceeds 260 characters, the script does not execute properly.

By default, the temporary cache is in your home folder, which may cause pathnames to exceed the limit. To work around this issue, create an environment variable in Windows called PEX_ROOT, a set the path to C:\user-sync\.pex. The OS uses this variable for the cache location, which prevents the path from exceeding the 260 character limit.


If that doesn't help, what version of windows are you on?

**Comment by adorton-adobe** [comment]
Could also be a 32/64bit issue.  Make sure you run w/ the 64bit version of the windows Python interpreter.

**Comment by adobeDan** [comment]
@StitchFurbix The dependencies you list as missing are all the ones in the build that are compiled for a specific processor platform (in python terms, the cp27-cp27m-win_amd64 platform, meaning C Python with math support on a windows platform using the amd64 processor architecture).  Typically, the reason they are shown as missing are that you are running a Python built for a different processor platform, for example Win32 (@adorton-adobe's suggestion), or that your hardware platform doesn't match (e.g., a non-amd64 platform, or one without extended math operation support).

Your best bet to get past this quickly is to verify that your hardware platform matches the build, and if so to download a new python from python.org that matches the build (as shown in adorton's comment).

If your hardware platform doesn't match our build, then you are best off doing your own build.  Doing this on Windows is a little tricky, because you need to install Cygwin (or another distribution such as Chocolate that can get you all the GNU build tools like compilers and make).

**Comment by StitchFurbix** [comment]
I fixed the issue with the execution as you all suggested.

Something must have gone wrong with the install the first time, once I uninstalled and installed 2.7.13 all is well.

Now I just have to get this all configured right lol

Thank you all for your help
