### ISSUE TITLE
--adobe-only-user-action exclude is not excluding them!

### ISSUE THREAD

**Issue by raymond-ensemble** [adobe-apiplatform/user-sync.py#134]
Users cce0, cce1, cce2, cce3....cce7 are all in the group CCE AD Group 1.
Users cce2 and cce3 are in the accessor group CCE Accessor Group 1.

**Steps**
1. Sync users from AD  with the group filter. **python user-sync.pex --users group "CCE AD Group 1" --process-groups** 
2. Sync users for the accessor group with the group filter. **python user-sync.pex --users group "CCE Accessor Group 1" --process-groups**

**Results**

1. All of the users are successfully created and have their groups assigned.

2a. In the owning org, users cce0, cce1, cce4, cce5, etc got their products removed.
2b. In the owning org, users cce2 and cce3 still have their groups assigned.
2c. In the accessor org, users cce2 and cce3 got their products assigned.

[2017-04-03.txt](https://github.com/adobe-apiplatform/user-sync.py/files/891607/2017-04-03.txt)
[user-sync-config.txt](https://github.com/adobe-apiplatform/user-sync.py/files/891610/user-sync-config.txt)

**Comment by adobeDan** [comment]
This is as-designed behavior.  Remember: for each user sync job, we look at ALL Adobe users, but we only match them against the input users of the job.  Since all the Adobe users except cce2 and cce3 did not match against the input users of the second job, and since you told the second job to process-groups for *all* Adobe users, all the managed groups were removed from all the Adobe users except cce2 and cce3.  If you ever want to restrict a sync job to operate only on the matched input users, then specify `--adobe-only-user-action exclude` to prevent changes to other users.

**Comment by adobeDan** [comment]
@raymond-ensemble Actually, it would be a great test if you would include --adobe-only-user-action exclude and make sure the other users are left untouched!!

**Comment by raymond-ensemble** [comment]
I just ran:
**python user-sync.pex --users group "CCE Accessor Group 1" --process-groups --adobe-only-user-action exclude**

The other users still have their products removed.

[log.txt](https://github.com/adobe-apiplatform/user-sync.py/files/891725/log.txt)

**Comment by adobeDan** [comment]
OK, thanks for the test!  Changing the name of the bug, and reopening it!
