### ISSUE TITLE
Excluded users are not are listed in the log, even at debug level, unless --process-groups is present

### ISSUE THREAD

**Issue by phil-levy** [adobe-apiplatform/user-sync.py#142]
Well, they aren't.

Upon more testing, it appears that the messages are not output unless --process-groups is also specified.  Including --adobe-only-users-action does not seem to trigger the messages.

At a minimum, the messages should be triggered by --process-groups or --adobe-only-users-action

**Comment by adobeDan** [comment]
I tried to make it so that excluded users are not logged unless there is some updated of an Adobe user happening that the exclusion might affect.  So if you say --update-users or --process-groups, for example, we log the excluded ones.  But I apparently missed the obvious processing, which is their deletion.  Oops.  I'll fix that.

**Comment by adobeDan** [comment]
Hmmmm, if the --adobe-only-user-action is exclude, should we log the user as being Adobe-only or being excluded? :)  I say Adobe-only.  What say you?

**Comment by adobeDan** [comment]
Never mind, I found a solution.  He's logged as both.

**Comment by adobeDan** [comment]
The more I run this, the more that I see the excluded users should always be logged, even if the command might not have updated them.  Especially because the summary says "Number of Adobe users excluded from updates" and that is never 0.

**Comment by adobeDan** [comment]
So this turned out to be a lot trickier than it looked.  But it's now fixed.
