### ISSUE TITLE
Documentation Item: removing a mapped group

### ISSUE THREAD

**Issue by phil-levy** [adobe-apiplatform/user-sync.py#145]
There is potential confusion when removing a mapped group.  Say a directory group mapped to the Adobe group Acrobat.  You think, "I no longer want to map this group to Acrobat" so you take out the entry.  The result is that all of the users are left in the Acrobat group because Acrobat is no longer a mapped group so user sync leaves it alone.  It doesn't result in removing all the users from Acrobat as you might have expected.

**Comment by adobeDan** [comment]
Yes, interesting.  Rather than just removing the Acrobat group from the map, you would need to add a new entry to the map with a directory group that no one is in (e.g., "null") and have Acrobat as its mapped Adobe group.  Then when you took Acrobat off the first group, it would stay a mapped group.

From a documentation perspective, you might want to recommend always have one directory group whose only function is to map to all the Adobe groups.  Like the "null" group I recommended above, no user would ever be expected to be in that group; it would exist just to declare the Adobe groups as being in the target of the map.

From a feature perspective, we might want to consider having an optional `target_adobe_groups` attribute (probably in the `adobe_users` section, like `exclude_adobe_groups`) for declaring the mapped groups on the Adobe side independent of their appearance on any given mapping entry.  (This would be similar to the `extended_adobe_groups` setting for extensions.)
