### ISSUE TITLE
name / first name fetched from AD, but not present on dashboard

### ISSUE THREAD

**Issue by Gor3t3x** [adobe-apiplatform/user-sync.py#148]
Hi,

When i run the script based on an AD group, i can see in the logs that the name, surname, userprincipalname is fetched, but when looking on the dashboard, some fields are empty (name and / or surname)

(Version 1.1.1)

exemple:
2017-04-06 14:16:51 5492 DEBUG umapi_client - Ran multi-user query: [] {} (page 1: 197 found)
2017-04-06 14:16:51 5492 INFO processor - Adding user with user key: xxx@xxx.be
2017-04-06 14:16:51 5492 INFO dashboard.owning.action - Added action: {"do": [{"createFederatedID": {"country": "BE", "option": "ignoreIfAlreadyExists", "email": "xxx@xxx.be"}}, {"add": {"product": ["adb_creativecloud"]}}], "requestID": "action_1", "user": "xxx@xxx.be"}
2017-04-06 14:16:51 5492 INFO processor - Adding user with user key: yyy@xxx.be
2017-04-06 14:16:51 5492 INFO dashboard.owning.action - Added action: {"do": [{"createFederatedID": {"lastname": "YYY", "country": "BE", "email": "yyy@xxx.be", "firstname": "XXX", "option": "ignoreIfAlreadyExists"}}, {"add": {"product": ["adb_creativecloud"]}}], "requestID": "action_2", "user": "yyy@xxx.be"}
2017-04-06 14:16:51 5492 INFO processor - Adding user with user key: testadb@xxx.be
2017-04-06 14:16:51 5492 INFO dashboard.owning.action - Added action: {"do": [{"createFederatedID": {"lastname": "ADB", "country": "BE", "email": "testadb@xxx.be", "firstname": "test", "option": "ignoreIfAlreadyExists"}}, {"add": {"product": ["adb_creativecloud"]}}], "requestID": "action_3", "user": "testadb@xxx.be"}
2017-04-06 14:16:53 5492 DEBUG requests.packages.urllib3.connectionpool - https://usermanagement.adobe.io:443 "POST 

see dashboard result
http://i.imgur.com/iw406P1.png

**Comment by adobeDan** [comment]
Thanks very much for this report!  We are very close to releasing 2.0 (2.0rc1 is posted right now), so we would like to make sure we find any bugs before we do that release.

There are two known configuration issues which can cause the behavior you are seeing.  I would like to explore each of them by asking you to run one more test for each.

First, I notice that your run did not use the `--update-users` command-line argument (because the actions are being set with `option` value `ignoreIfAlreadyExists`).  Can you please try to do the same run again (with the existing users, who are already added to your organization) but this time specify `--update-users` and check to see whether the given name and surname are updated correctly?  If they are, then we can rule out one possible cause for this problem.

Second, I would like to verify that the users you are sending have had their accounts removed not only from your Users list but also from the underlying Adobe account database.  Can you please go into the Admin Console and find these users *not* in the overall Users list but by going through the identity panel to their particular domain and finding them in the Domain Users tab.  When you have found them, select them and delete them (by hitting the minus icon).  [NOTE: this will remove any cloud storage associated with their account, so please be sure you try this with **test users only**.]  Then try re-adding them using the exact same run you did originally.  If they are added with their correct surnames and given names, then we will have found the problem (which is a known issue that Adobe is fixing on the server side).

**Comment by Gor3t3x** [comment]
Damn!

The first run did update the infos like you said. (python user-sync.pex --users group ADB_CREATIVECLOUD --process-groups --update-user-info)

the second run after deleting users in the DB with only --users group ADB_CREATIVECLOUD and --process-groups worked and all fields are updated.

In production if i want the users on dashboard and my AD group to be the same, i would use the command :
python user-sync.pex --users group ADB_CREATIVECLOUD --process-groups --remove-nonexistent-users right?

Thanks for your time and looking forward to test the new release.

**Comment by adobeDan** [comment]
Sorry for the late reply; I was in meetings all day 👎.  I'm glad this was resolved for you.

So the 1.1.1 release is a little tricky in the way `--remove-nonexistent-users` works with `--users group` (and `--users mapped`), because it will think that *every* Adobe-side user that doesn't match a user in your ADB_CREATIVECLOUD group should be removed from the organization on the Adobe side.  This includes not only your Enterprise ID/Federated ID users that you originally sync'd in via User Sync, but also any Adobe ID users (such as your sysadmins), and any users that other admins may have added manually.  This is probably not what you want :(.

For as long as you are still on the 1.1 release, I would recommend that you do the following:

* define a user group (say "Creatives") on the Adobe side that you sync the ADB_CREATIVECLOUD users to;
* give that Creatives user group on the Adobe side any product entitlements that the users should have; and
* run the sync tool with `--users group ADB_CREATIVECLOUD --process-groups --update_user_info` *only*.

If you do it this way, you won't end up removing any users accidentally, but any users that you take out of the group on your side will lose their membership in the Creatives user group and thus all of their product entitlements.  So you will still see them in the organization on the Adobe side, but they won't be able to log in, and if you ever add them back into the group on your side they will get re-entitled.

In the 2.0 release we are providing much more fine-grained controls over which users on the Adobe side are exempted from User Sync updates, as well as many more user deletion options, and it will be lot easier for you to run User Sync and remove just those users you meant to remove. :)  If you look at the docs that are currently posted on the [docs site](https://adobe-apiplatform.github.io/user-sync.py/) you can see all the new capabilities, and all of them work in the 2.0 RC builds we are posting.

Good luck, and feel free to open new issues if you have any issues or other questions!
