### ISSUE TITLE
"--remove-nonexistent-users" only applies to Federated users 

### ISSUE THREAD

**Issue by adorton-adobe** [adobe-apiplatform/user-sync.py#16]
The `--remove-nonexistent-users` command-line param only applies to Federated users.  Should it also work for Enterprise users?  

For details, see https://github.com/adobe-apiplatform/user-sync.py/issues/9#issuecomment-278899297

**Comment by adobeDan** [comment]
@phil-levy You asked "does anyone know why we don't remove enterprise users"? in #9; I'm answering here since Andrew opened this issue for that question :).

My answer: no idea.  It seems like a bug to me that we are treating Enterprise IDs and Federated IDs differently.  I believe they should be treated exactly the same in all aspects of sync.

**Comment by phil-levy** [comment]
This is a change we want to make, but it will come in the next batch of change requests, so closing this issue for now.

**Comment by adobeDan** [comment]
Looks like this bug
