### ISSUE TITLE
Unrecognized column names warning when trying to use --config-file-encoding utf8

### ISSUE THREAD

**Issue by raymond-ensemble** [adobe-apiplatform/user-sync.py#180]
When I tried to sync from a user-file.csv with specials characters like "ç" "é" "è" and using --config-file-encoding utf8, I would get this:

**WARNING csv - In file 'users-file.csv': unrecognized column names: ['\xef\xbb\xbffirstname']**

Somehow, it's adding "\xef\xbb\xbf" in front of the firstname.

[2017-05-05.txt](https://github.com/adobe-apiplatform/user-sync.py/files/980525/2017-05-05.txt)
[users-file.txt](https://github.com/adobe-apiplatform/user-sync.py/files/980527/users-file.txt)

**Comment by adobeDan** [comment]
Hey @raymond-ensemble, thanks so much for testing this right away!

I'm guessing that `firstname` is the header for your first column.  Those three characters in front (`'\xef\xbb\xbf'`) are the UTF-8 encoding of what's called the _BOM_ or _byte-order mark_: the actual hex sequence is `0xFEFF`.  The BOM is a required element in UTF-16 and DBCS encoded files, used to indicate whether the file system is big-endian or little-endian.  But guess what: the BOM is illegal in UTF-8, which is a byte-stream rather than a word-stream format.  So whatever editor you are using to create the UTF-8 file is putting a BOM at the front of the file, and it shouldn't be.

Many editors that are Unicode-capable have a preference for whether to write the BOM or not, and not all of them are smart about which formats allow a BOM.  Try turning the BOM off in your editor and seeing if that fixes the issue.  Please report back about what you find.  And thanks again for testing!

**Comment by raymond-ensemble** [comment]
It's working after I changed the encoding to UTF-8 without BOM. However, I noticed that in the logs, it says:

**INFO processor - Updating info for user key: enterpriseID,ccewin1@ensemble.ca, changes: {'firstname': u'!CCE_win_\xe7\xe9\xe8'}** 

The firstname for that person is correctly displayed in the admin console though. The first name shows **!CCE_win_çéè**.

**Comment by adobeDan** [comment]
What's being displayed in the log is the utf-16 version, which is the format Python uses internally for Unicode strings.  This looks like it's performing as designed.
