### ISSUE TITLE
Users don't get removed from old product configuration (adobe_group or PC)

### ISSUE THREAD

**Issue by bajwa-adobe** [adobe-apiplatform/user-sync.py#194]
The users don't get removed from old product configuration (PC), when we update them on new product configuration. 

I had following mappings setup

    - directory_group: "TestGroup1"
      adobe_groups:
        - "Default Acrobat Pro DC configuration"

Where "TestGroup1", has two users

Now I changed adobe_groups from "Default Acrobat Pro DC configuration" to "Default Photoshop CC - 5 GB configuration" and ran the user sync tool with following command.

python user-sync.pex --process-groups --users mapped 

It added "TestGroup1" (two users) to new product configuration "Default Photoshop CC - 5 GB configuration" but failed to remove them from old product configuration "Default Acrobat Pro DC configuration" 

Is that expected behavior? I had assumed that they should exist only on final product configuration (PC), but not both.

Here are attached files 
S1.png - State of Admin Console before change
S2.png - State of Admin Console before after
1_user-sync-config.yml.txt - First config
2_user-sync-config.yml.txt - Final config

<img width="960" alt="s1" src="https://cloud.githubusercontent.com/assets/28625684/26006223/8a1b9bd4-3733-11e7-8c44-483eb73f4eae.png">
<img width="960" alt="s2" src="https://cloud.githubusercontent.com/assets/28625684/26006222/8a183e08-3733-11e7-927b-c13fa94e58c8.png">

[1_user-sync-config.yml.txt](https://github.com/adobe-apiplatform/user-sync.py/files/997301/1_user-sync-config.yml.txt)
[2_user-sync-config.yml.txt](https://github.com/adobe-apiplatform/user-sync.py/files/997300/2_user-sync-config.yml.txt)

[2017-05-12.log.txt](https://github.com/adobe-apiplatform/user-sync.py/files/997304/2017-05-12.log.txt)

**Comment by phil-levy** [comment]
This is actually expected behavior.  When the group Default Acrobat Pro DC configuration gets removed from the mapping, it basically says "this group is no longer managed by user sync" so the users don't get removed.  The group Default Acrobat Pro DC configuration becomes like any other group that user sync is not aware of: it is left alone.  

This is covered in the manual with a suggestion about how to deal with it: 
https://adobe-apiplatform.github.io/user-sync.py/user-manual/#removing-group-mappings

I had to scratch my head about this myself the first time I ran into it.
