### ISSUE TITLE
Can't figure out how to store private key in Windows Credential Store

### ISSUE THREAD

**Issue by phil-levy** [adobe-apiplatform/user-sync.py#198]
Doesn't seem to take multi-line value, or long string if I put on one line.

**Comment by bhunut-adobe** [comment]
Phil,

I can't do it via GUI or command line. I got an error. The specified password has exceeded 512 bytes

I count of characters in my private.key and came up with 1612 characters.

This is the command I try it with.
Powershell V5+ Command
```
Install-Module CredentialManager
New-StoredCredential -Target 'secure_priv_key_data_key' -UserName 'umapi_private_key_data' -Password "$(Get-Content C:\User-Sync-Tool\private.key)"
```

**Comment by adobeDan** [comment]
The default CredentialManager module has a built-in length limit of 512 chars.  I've asked the developer whether this is an underlying technology limitation.

**Comment by adobeDan** [comment]
It looks like the credential manager on windows has no easy way to store credentials larger than 512 chars.  The API allows it, but none of the interfaces do.  So I think the way to make this work on Windows (and all platforms) is to allows an encrypted private key in the PEM format and to store the key password in the keychain, rather than the key itself.
