### ISSUE TITLE
How to fix failed: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661) error

### ISSUE THREAD

**Issue by Stancicle** [adobe-apiplatform/user-sync.py#204]
I have checked both the private and public key that I'm using and generated multiple times from a pfx file. I still keep getting this error. Any other things I could try to resolve this problem?

**Comment by adobeDan** [comment]
Hmmmm.  Does this happen when you try to connect to your LDAP or Active Directory server?  If so, you probably have set `require_tls_cert` to `True` in your LDAP config file.  This doesn't work the way you expect, because it requires the TLS connection to use a certificate whose entire signing chain is in your SSL store (which it almost never is).  And that setting is _not_ required to use SSL for LDAP connections.  So I recommend you turn it back to `False`.

If that wasn't the issue, please attach a debug log to this issue so we can give you better help.

**Comment by Stancicle** [comment]
`require_tls_cert` is set to `false`. 
Here is the log. [2017-06-08.txt](https://github.com/adobe-apiplatform/user-sync.py/files/1062452/2017-06-08.txt)

The command I've been running to test `python user-sync.pex -t --users mapped --update-user-info --process-groups`

**Comment by adobeDan** [comment]
Thanks for the log.  It's actually your connection to the Adobe user management server that's failing with a certificate failure, which I've never seen.

Can you please try going to https://usermanagement.adobe.io/v2/usermanagement in a system browser on the same machine you are running User Sync?  Normally you would get a correctly-terminated secure connection and a 404 (file not found) error.  But since User Sync on that machine is failing to verify the server certificate, I'm hoping the browser also will, and that it will give you a lot more information about why the failure is happening.

**Comment by bhunut-adobe** [comment]
@adobeDan - I believe I was working with this customer earlier today. We verified by going to that URL on the browser and get 404 error. We also inspected the SSL certificate of that website and it was able to verify.

@adorton-adobe is also having the same issue with another customer.

**Comment by adobeDan** [comment]
So User Sync uses the [python requests](http://docs.python-requests.org/en/master/) library to make its server calls, and this library uses openSSL to do the certificate validation, as explained in [this section of the docs](http://docs.python-requests.org/en/master/user/advanced/#ssl-cert-verification).  Please check that your system's installation has the necessary server signing certificate for Adobe I/O (Digicert Global Root CA) in its system-level certificate bundle.  (On many systems, the SSL certificate bundle is far more restricted than the those used by the browsers.)

**Comment by adobeDan** [comment]
@bhunut-adobe @Stancicle Any progress on checking SSL certs on the affected system?

**Comment by bhunut-adobe** [comment]
@adobeDan:   @adorton-adobe and I just worked with another customer who had the same issue. We were able to verify this is a network issue. The customer was able to verify the certificate by using the external network (LTE Hotspot).  @Stancicle Please verify with your network team to see if there is a security protocol that is preventing cert verification.

**Comment by Stancicle** [comment]
@bhunut-adobe For that customer that had the same problem, which URL exception did they put into their firewall? On our end, we have white-listed ims-na1.adobelogin.com and https://usermanagement.adobe.io/v2/usermanagement and we still see the error.

**Comment by adobeDan** [comment]
@Stancicle You will likely need to exempt the certificate authority for the root signing certificate, so that the CA (DigiCert) can be contacted to make sure the web server certificate is being used correctly and has not been revoked.  I suggest you do what I'm guessing @bhunut-adobe did for the other customer: run user sync from a machine that's outside of your firewall (using a CSV file as input so it doesn't try to contact your LDAP server) and then do a network trace to find out what endpoints are being contacted during the connection setup with usermanagement.adobe.io.

**Comment by Stancicle** [comment]
Thank you for the suggestions, but at this point in time I'll stop testing the software due to mounting work, and our current method is working as it should (SSO). I'll re-visit this once things have died down a bit. Please close this thread if need be on your end.

**Comment by bhunut-adobe** [comment]
Additional to this issue: 

Python requests library on windows use CA bundle instead of Windows Cert Store 
Since UST package everything in PEX file. CA Bundle located here

`[User Sync Tool Path]\.pex\install\requests-2.13.0-py2.py3-none-any.whl.59dc5c6338fb72ca09dcf97dda36a7aaa5d6bd0e\requests-2.13.0-py2.py3-none-any.whl\requests\cacert.pem`

If you have SSL inbound inspection or forward proxy enabled on the firewall. I think you would need to point Python requests CABundle to Firewall CA cert

if your firewall CA cert is in DER format. you will need to use this command to convert to pem.

`openssl x509 -inform DER  -in firewallcert.crt -out firewallcert.pem -outform PEM`

Create environment variable name: REQUESTS_CA_BUNDLE
with the path to firewallcert PEM file.

**Comment by adobeDan** [comment]
Ah, yes, excellent advice @bhunut-adobe!  I had completely forgotten about the many firewalls that do SSL termination and re-establishment on the outbound so that they can do packet inspection!

I am going to mark this issue as a question and close it, but @Stancicle if you ever return to this issue and need more help feel free to reopen it (or open a new one referencing this one)!
