### ISSUE TITLE
404 Error  - User Manual 

### ISSUE THREAD

**Issue by chad-fox** [adobe-apiplatform/user-sync.py#220]
The link for the User Manual on the user-sync.py page gives a 404 error.

https://adobe-apiplatform.github.io/user-sync.py/user-manual/

The following link with /en/ added works:

https://adobe-apiplatform.github.io/user-sync.py/en/user-manual/

**Comment by adobeDan** [comment]
Hey @phil-levy can you be sure to fix the README before tomorrow's release?  Thanks!

**Comment by adorton-adobe** [comment]
Can we set up https://adobe-apiplatform.github.io/user-sync.py/user-manual/ to redirect to https://adobe-apiplatform.github.io/user-sync.py/en/user-manual/ (and same for the Success guide)?  We've got a number of pieces of sales/marketing collateral with the non-localized User Manual and Setup and Success Guide.

**Comment by phil-levy** [comment]
Is this because that is where the user manual used to be and people have links to it?

**Comment by adobescarr** [comment]
Hey @phil-levy and @adorton-adobe - I've just found this 404 and realised it's due to multi-language support. As a POB PM I and the rest of the team constantly use different direct links within many presentations and are often sent via email or within meeting invites during project kick-off and consultation sessions. Therefore many customers across EMEA and AMER have these links and will be hitting 404's. 

Adding redirects will be greatly appreciated. 

Many thanks,
Steve Carr
