### ISSUE TITLE
Proxy Authentication Support

### ISSUE THREAD

**Issue by bhunut-adobe** [adobe-apiplatform/user-sync.py#261]
A customer requests an ability to add Proxy Setting within UST. 

https://github.com/adobe-apiplatform/umapi-client.py/issues/52

**Comment by adobeDan** [comment]
We use the OS network stacks, all of which (to my knowledge) provide both proxy and proxy-authentication capabilities. I'm marking this wontfix and will close it in a week unless someone shows me an OS we run on that has no authenticated-proxy support.

**Comment by adobeDan** [comment]
Closing as per prior comment.

There is a very common misconception that Windows 10 proxying does not support proxy authentication.  In fact it does, but the authentication is managed in Windows Credential Manager rather than in the proxy settings.  Basically, you configure your proxy host/port in the Proxy settings, and then you configure an Internet Credential with the username and password for that host in Windows Credential Manager.  It’s a little hard to find good documentation for this process; the best I’ve found with a quick search is [this article on the Windows forums](https://answers.microsoft.com/en-us/windows/forum/windows_10-networking/adding-credentials-to-windows-proxy-settings/d6fdab82-6163-4aad-8133-43f7706ceb9c).
