### ISSUE TITLE
--update-user-info case sensitive for Email field

### ISSUE THREAD

**Issue by bhunut-adobe** [adobe-apiplatform/user-sync.py#281]
An issue where an account Email Address in the Admin Console is all upper case. 
When running --update-user-info it saw that the case in the AD is lower but Admin Console is upper so it attempted to update the email but failed.
 
I was not able to correct email address on the admin console. I even attempted to delete and re-add but the case still the same.

should --update-user-info be case insensitive for email address field?

**Comment by bhunut-adobe** [comment]
@phil-levy @adobeDan Just following up on this.

**Comment by adobeDan** [comment]
@bhunut-adobe Sorry for the delay in reply, Kevin.  This is a known issue about how emails are handled on the server side: they are compared case-insensitively but stored case sensitively.  So once they are set you cannot make case changes (either from the console or the UMAPI) because the new email is considered to be the same as the old.

The reason removing the user from the org and then re-adding didn't work is that removing the user from the org doesn't delete the account from the directory, so when you re-added it was the same user account that comes back.  You would have to go to the "Domain Users" tab and delete the user there in order to really delete the account from the directory.  Then re-adding with the correct case works.

So this is as designed, albeit frustrating.  To change the user's email case, you have to change the email completely to a different email, then change it back but with the right case.
