### ISSUE TITLE
User sync creating duplicate accounts in the Admin Console

### ISSUE THREAD

**Issue by sjonetAMFAM** [adobe-apiplatform/user-sync.py#282]
PLATFORM:  Windows Server 2012 R2 x64
PYTHON:  2.7.13 x64
UST: 2.2.1

I have several users who have pre-established Adobe IDs whose Admin Console accounts I don't want to alter with the user sync tool. These users are, like the users who I DO want to sync in as Federated IDs, members of security groups that I'm syncing in with the tool. I was told that, because they have Adobe IDs, Federated IDs would not also be created for them with the sync, despite their group membership, however this is not working as expected, as duplicate Federated IDs were created for all users who already had Adobe IDs, despite:

  exclude_identity_types:
    - adobeID
    - enterpriseID 

being in my user-sync-config.yml file.

The command-line I used for the sync is (from within C:\AdobeUserSync):

C:\Python27\python.exe user-sync.pex --users mapped --update-user-info --process-groups --adobe-only-user-action remove

Is this a bug? If so, how does it get resolved? If not, what should I change in my configuration so that I can keep ALL users members of the appropriate NT security groups that help us track software licensing on our side, while not creating duplicate accounts on the Admin Console side if they already have Adobe IDs?

Thank you,
Shane Jonet

**Comment by adobeDan** [comment]
Hi Shane,

The User Sync tool, unless you configure it otherwise, assumes all users on the client side should be mapped to users of a single type on the Adobe side.  That type is given by the `user_identity_type` configuration parameter in the `directory_users` section of the main config file, and it defaults to `enterpriseID`.  It sounds like you may have set that parameter to `federatedID`, in which case the tool will try to create Federated ID users for each of your directory users, regardless of whether or not a user with the same email address already exists in your console as an Adobe ID.

If you have users in your directory that you know should have a different type on the Adobe side, then you can specify the `user_identity_type_format` parameter in your LDAP config file to be the name of an attribute in your directory that contains the appropriate type for each user.  So, for example, you might add an attribute "identity_type" to each user in your directory, set the `user_identity_type_format` parameter to have the value `{identity_type}`, set that attribute value for your Adobe ID users to `adobeID`, and set that attribute value for all your other users to be `federatedID`.  This would sync the users in the way you desire.

There is documentation on the user of this parameter in the [example LDAP configuration file](https://github.com/adobe-apiplatform/user-sync.py/blob/v2/examples/config%20files%20-%20basic/3%20connector-ldap.yml) in the repo.

Hope this helps! -d.
