### ISSUE TITLE
Error when setting default_country_code: NO

### ISSUE THREAD

**Issue by madumro** [adobe-apiplatform/user-sync.py#291]
According to ISO 3166, the Norwegian Country Code is NO. But when setting **default_country_code: NO**, the UST returns this error:
**CRITICAL main - Value should be one of these types: ['str'] for key: default_country_code in: <user-sync-config.yml>.directory_users**
This can be worked around by adding double quotes around "NO". But can it be fixed inside the code?
Thank you!

**Comment by adobeDan** [comment]
Unfortunately, it is YAML itself (the file format for configuration files) that treats all case-variant forms of "Yes" and "No" specially: reading them as the values "True" and "False".  Since we chose YAML for our config files precisely because it's a standard format with wide support in the industry, we don't want to introduce variant handling for specific cases.

(Yes, Adobe realizes how English-centric this aspect of YAML syntax is, and its adoption of YAML for User Sync should not be interpreted as an endorsement of this or any aspect of the standard.)

For a brief intro to YAML string quoting, see this [StackOverflow answer](https://stackoverflow.com/a/22235064/558006).  Speaking only for myself, I strongly agree with one of the comments on the answer, which says _Given all these caveats, I'd rather just use quotes everywhere_.
