### ISSUE TITLE
Windows Release in Zip format instead tar.gz

### ISSUE THREAD

**Issue by bhunut-adobe** [adobe-apiplatform/user-sync.py#345]
Is it possible for future windows release to use ZIP instead tar.gz format

This will eliminate the requirement for 7-zip application on Windows

**Comment by bhunut-adobe** [comment]
Also for Example configs example if possible

**Comment by adorton-adobe** [comment]
Is there any reason we can't release a bare pex file?  A pex file is basically just a fancy zip file (like a jar).   We aren't gaining anything compression-wise by zipping a zip file, and we aren't including anything else with the pex that would need to be part of an archive.  The only reason it would make sense is if Github has restrictions on what file types are allowed in releases.

If it would be better to keep the pex file in a zip or tar.gz, then I agree that Windows releases should be released in .zip files.

For the example configs, we'd probably want to continue to offer .tar.gz in addition to .zip, since unzip isn't always installed on some Linux distros by default.

(also - if we do offer the example configs in .zip, can those files be saved with CRLF line endings?  many Windows customers I work with edit their configs in Notepad)

**Comment by adorton-adobe** [comment]
We'll plan to add a Windows release zip (in addition to .tar.gz) to 2.3, and will provide the example configs in zip format (also in addition to .tar.gz).
