### ISSUE TITLE
Custom Attributes and Mappings

### ISSUE THREAD

**Issue by Tomomi99145** [adobe-apiplatform/user-sync.py#347]
What is "bc" and "subco" set with extended_attributes key?

**Comment by Luci2015** [comment]
bc and subco are just examples of AD attributes (extended because we already look at some specific ones like 'c' for country, 'mail', 'givenName' )
If you want to check out all AD attributes you could open a PowerShell instance and type:
`Get-ADUser username -Properties * | Select *`
Replace username with a value for an existing user to get the whole list of attributes.

Check out this help page: 
https://adobe-apiplatform.github.io/user-sync.py/en/user-manual/advanced_configuration.html#adding-custom-attributes
