### ISSUE TITLE
Update logging to reflect accurate user key

### ISSUE THREAD

**Issue by adorton-adobe** [adobe-apiplatform/user-sync.py#363]
The user key used in [certain log entries](https://github.com/adobe-apiplatform/user-sync.py/blob/v2/user_sync/rules.py#L431) reflects the directory user record.  Elements of the key - username, domain, email - can be updated by the after_mapping_hook.  When any key element is updated, the key used in log messages is not updated.  This can cause confusion - see #362.

Before writing the key to the logger, we should update it to reflect the umapi record.  We don't necessarily need to update the key itself, which is used in internal data structures.  At the very least, we should modify its representation when adding it to logs (perhaps with a new lookup table).

**Comment by adorton-adobe** [comment]
@shasibhusanJena FYI - the links here and in the linked issue that point to specific lines in the source code are out of date.

**Comment by shasibhusanJena** [comment]
oh ok.  help me how can I produce same bug while running on my local
do I have to enable extension-config.yml to reproduce this change with below lines enabled under  after_mapping_hook: |

if below changes I do have to enable to see this error on my local
  student_email = source_attributes.get('OCADstudentEmail')
  if student_email is not None:
    target_attributes['email'] = student_email
    target_attributes['domain'] = student_email.split("@")[1]
  print(source_attributes)
  print(target_attributes)

**Comment by shasibhusanJena** [comment]
I feel this is what we are trying to find out why this key getting 'none'

ex:
{'email': 'user123@faculty.ocadu.ca', 'identity_type': **None**, 'username': 'user123', 'domain': None, 'givenName': 'User', 'sn': '123', 'c': 'CA', 'OCADstudentEmail': 'user123@student.ocadu.ca'}

2019-02-11 21:19:04 17504 DEBUG processor - Source attrs, before: {'email': 'deepak_kumar@adobeccetest.com', 'identity_type': **None**, 'username': None, 'domain': None, 'givenName': 'deepak', 'sn': 'kumar', 'c': None, 'bc': None, 'subco': None}

Need to check why identity_type setting to "none" instead of printing correct identity_type 
i beleive i have to work on one among them below
after_mapping_hook_scope['source_attributes'] , after_mapping_hook_scope['target_attributes'] 
or   def log_after_mapping_hook_scope(self, before_call=None, after_call=None):
@adorton-adobe  please correct me if my understnading is wrong.
