### ISSUE TITLE
Python 3.7.0 

### ISSUE THREAD

**Issue by Luci2015** [adobe-apiplatform/user-sync.py#376]
The .pex package for Windows fails to run the script with the newest Python 3.7.0 version.
The error is the one with missing dependencies.
I see all the Win builds are constructed using Python 3.6.3.

**Comment by janssenda-adobe** [comment]
When the pex file is created, the major python version is stamped at the top.  Unfortunately this means it will only run if it matches the environment version. This is a pex thing, and I have not found a way to override it.  I think you need to build it on 3.7 to run it there.

**Comment by adorton-adobe** [comment]
We're not targeting Python 3.7 for Windows at this time.  Because the python-ldap library is difficult to build on Windows (and no wheel files are on PyPI for python-ldap win64), we rely on an unofficial build.  The python-ldap version we use only has builds for Python 2.7, 3.4, 3.5 and 3.6.

We can get a build that targets 3.7, but it's a newer version of the library than the one we use (3.1.0 vs 2.4.45).  It might be worth the effort to test 3.1.0 so we can do a 3.7 build, but not until a future release.

**Comment by Luci2015** [comment]
OK, the report is just to mention it, in case someone else searches for this until the enhancement is released.

**Comment by adorton-adobe** [comment]
Depends on #436

**Comment by adorton-adobe** [comment]
Closing this as we're planning on transitioning to drop pex in the future in favor of standalone executables that won't depend on an external Python interpreter.
