### ISSUE TITLE
Handle config shell commands safely

### ISSUE THREAD

**Issue by adorton-adobe** [adobe-apiplatform/user-sync.py#390]
There's a mechanism that can be used in the `user-sync-config.yml` where instead of linking to a connector config file, you can specify a shell command that would output a YAML config to stdout, which would be loaded by the config module.

The current approach to this is to parse the command from the `$(` and `)` markers and run the command with `subprocess.check_output()` with `shell=True`.  This is potentially dangerous because it allows arbitrary code execution.  The risk is fairly low because modifying a config file would presumably require privileged access to a system.  It would still be a good idea to make this call safe.

To make it safe, we should parse the command string with the `shlex.split()` and run the command with `shell=False`.

NOTE: This will need some special attention in Windows.  The split command should be able to handle windows commands with posix=False, but we'll need to make sure.

**Comment by adobeDan** [comment]
The proposed fix doesn’t actually change the threat. Just because you are parsing the command doesn’t mean it isn’t any arbitrary command. Anything the shell would accept will be accepted by this method.

Any ability to execute an arbitrary command from the config file offers the same attacking surface.

Typed on a tiny keyboard. Please excuse typos.

________________________________
