### ISSUE TITLE
ldap key not recognized or emits spurrious message

### ISSUE THREAD

**Issue by phil-levy** [adobe-apiplatform/user-sync.py#4]
This appears in the example config files but when uncommented result in the following message:

2017-02-01 14:43:53 14292 WARNING config - Found unused keys: ['ldap'] in: <user-sync-config.yml>.directory.connectors

**Comment by jamesg123** [comment]
Hi Phil,

I can recreate this when the '--users' command line option is not specified. Can you confirm whether or not you specified this option when you received the error?

Thanks,
Jim

**Comment by phil-levy** [comment]
I probably ran it with --users file f as opposed to --users all or no --users.

phil

**Comment by jamesg123** [comment]
Hi Phil,

Are you able to recreate and let me know the command line and config used?
I couldn't get the error to come out when --users is specified

Thanks,
Jim

**Comment by phil-levy** [comment]
python user-sync.pex --users file example.users-file.csv --process-groups
2017-02-05 22:57:14 8248 INFO config - Using main config file: user-sync-config.yml
2017-02-05 22:57:14 8248 INFO main - ========== Start Run =======================================
2017-02-05 22:57:14 8248 WARNING config - Found unused keys: ['ldap'] in: <user-sync-config.yml>.directory.connectors


user-sync-config.yml:

dashboard:
  owning: "dashboard-config.yml"
directory:
  connectors:
    ldap: connector-ldap.yml
   groups:
    - directory_group: acrobat_pro_dc
      dashboard_groups: 
        - Default Acrobat Pro DC configuration
    - directory_group: all_apps
      dashboard_groups:
        - All Apps
  user_identity_type: enterpriseID
logging:
   log_to_file: True
   file_log_directory: logs
   file_log_level: debug

**Comment by jamesg123** [comment]
@phil-levy Thanks for that. I can recreate the issue now.

The reason this is happening is due to the --users file option being passed when ldap configuration exists in the config.yml.

In config.py we can see the following:


`    def get_directory_connector_options(self, connector_name):
        '''
        :rtype dict
        '''                
        connector_options = {}
        connectors_config = self.get_directory_connector_configs()
        if (connectors_config != None):
            connector_item = connectors_config.get_list(connector_name, True)
            connector_options = self.get_dict_from_sources(connector_item, 'directory[%s]' % connector_name)`

When –users all is specified on the command line, the connector_name is ldap, we get the ldap key from the config dictionary (mark it as accessed) and no error is reported.

When --users file <filename> is entered, connector_name is csv (not ldap). This results in the ldap key being present in the config dictionary, but never marked as accessed. The config values are then checked to ensure they were all accessed in check_unused_config_keys and we get the warning:
Found unused keys: ['ldap'] in: <user-sync-config.yml>.directory.connectors

The warning is suggesting that the ldap configuration isn't being used (which it isn't).

**Comment by phil-levy** [comment]
That seems reasonable enough.  No need for further action on this.
