### ISSUE TITLE
Please tell me about using G-Suite again.　

### ISSUE THREAD

**Issue by Tomomi99145** [adobe-apiplatform/user-sync.py#415]
Please tell me about using G-Suite again.　#408 

>The option would be to connect G-Suite to a third party LDAP service and connect the tool to that or export the users from G-Suite to csv and feed the tool the csv file as the user source - the tool can handle that.

Is there a usecase to connect G-Suite by connecting to a third party LDAP service.
Also, is it free to use third party LDAP service?
I would like to know if there are usecase using it for free.

regards,

**Comment by adorton-adobe** [comment]
Unfortunately, since the sync tool doesn't support G-Suite, we can't offer support on it.  I recommend asking this in a G-Suite discussion forum.

I believe Google also has an API for retrieving G-Suite users.  It may be easier to just get a list of users from that system and converting it to a CSV that can be used by the sync tool.
