### ISSUE TITLE
About domain name conversion using UST.

### ISSUE THREAD

**Issue by Tomomi99145** [adobe-apiplatform/user-sync.py#417]
Please let me know, can I convert domain name using UST.

For example,
aaa@adobetest.com is registered in Active Directory.
Sync aaa@adobetest.com with the Admin console using UST.
I want to register as aaa@adob.com.

Best regards,

**Comment by Luci2015** [comment]
One way to go is that you should take a look from what AD attribute that "aaa" value comes from (maybe **sAMAccountName**?) and you could build the email format in the connector-ldap.file such as: `user_email_format: "{sAMAccountName}@adobe.com"`
Replace sAMAccountName with whatever serves your purpose.
The above forces ALL your users to have @adobe.com domain in their email and use the sAMAccountName for initial part. 

If you are extracting users with different domains in their mail, but need just one of them to be modified (ex: adobetest.com), then you might want to enable the extension.yml file and change the code inside `after_mapping_hook: |` so that a check is done if the domain of the user mail equals adobetest.com and if true then set `target_attributes['email']` to have the adobe.com domain instead of adobetest.com

**Comment by adorton-adobe** [comment]
The extension hook solution will not work completely because user comparison will be done before the hook is executed.  The comparison would be made against the unmodified email address.

@Tomomi99145 - what is the exact problem you're trying to solve?

**Comment by takenalias** [comment]
> The extension hook solution will not work completely because user comparison will be done before the hook is executed. The comparison would be made against the unmodified email address.
> 
> @Tomomi99145 - what is the exact problem you're trying to solve?

I have a similar issue. Basically, users have their email address in the format of user@domain1.com but I need to change it to be user@domain2.com. As the users are federated, ADFS current translates the domain part and the federated domain in the console is registered agains @domain2.com

What would be the best way to go about this @adorton-adobe  ?

**Comment by adorton-adobe** [comment]
@takenalias If you just need to do a one-off update, you'll probably want to write a script that uses the UMAPI to update the email address and ensure your sync config uses the same attribute to for user ID.  You may also be able to use the CSV bulk edit tool instead.
