### ISSUE TITLE
Multiple LDAP Groups found

### ISSUE THREAD

**Issue by jamesosteen09** [adobe-apiplatform/user-sync.py#446]
So my organization has been running this script with no problem for months. All log files show a successful finish. Then one day out of the blue I notice my user log files starts showing the entire sync wasn't finishing and I'm getting the error "Multiple LDAP Groups found for: ". Every day since Jan 10th it's the same old thing except the group named in the error changes. Funny thing is out of 96 groups it read it's only two that keeps showing up in the error. One day it's this one and the next its that one. They just keep rotating days. There's been no change to my script and no change to my AD groups or LDAP settings. So not sure why the problem would just start out of nowhere. Tonight I'm going to try and block those two groups out of the script and see how it runs then. Any other ideas as to why this started happening? Anything I need to update on the script?

**Comment by adorton-adobe** [comment]
Interesting.  My initial guess is that the Sync Tool isn't the issue if you haven't upgraded to a new version or modified your config.  Will you please provide the following details?

* Command you're using to invoke the tool e.g. `user_sync --process-groups --users mapped`
* OS you're using to run the tool
* Python version
* User Sync Tool version
* LDAP system (e.g. Active Directory)
* Have you made any changes to any of the LDAP query settings in `connector-ldap.yml`?

If you're running it with `--users mapped` then the Sync Tool needs to look up the distinguished name for each LDAP group in order to query the members of each group.  The error you've referenced is raised when the LDAP connector gets an unexpected result from the LDAP server when the DN lookup query is performed.  My guess is that your LDAP system is returning more than one result when looking up the group DN.

**Comment by adorton-adobe** [comment]
@jamesosteen09 if you're still seeing this issue, please provide the information I requested.  Otherwise let me know if I can close this.

**Comment by jamesosteen09** [comment]
Thanks for the reply man. I ran several tests over the last few days, removing groups one at a time from the sync script and rerunning it. I narrowed down the exact groups triggering the error and sure enough when I searched our AD there was a newly created duplicated group. Some program's automated process is to blame. The user sync script still works as expected so feel free to close. Thanks!
