### ISSUE TITLE
Group removal issues

### ISSUE THREAD

**Issue by SocalTech471** [adobe-apiplatform/user-sync.py#447]
My setup is pretty basic with a user group created which I then add users too and assign products to the group itself.  New users are being assigned without issue but users that need to have their license stripped and be removed from the group is causing an error.   I"m currently running 2.3.

Product Group1  (This group is assigned to User Group1)  
User Group1 (  Users all listed in this group)

My sync logs are returning this error.
ERROR umapi.action - Error in requestID: action_31 (User: {'user': '#######@######.org', 'requestID': 'action_31'}, Command: {'remove': 'all'}): code: "error.group.remove_failed" message: "remove [#######@######.org] to product group Product Group1_0CFE9FE-provisioning failed: error.group.remove_failed"

My command parameters:

python user-sync.pex --users mapped --process-groups --adobe-only-user-action remove-adobe-groups

My configuration:

directory_users:
  user_identity_type: federatedID
  default_country_code: US
  connectors:
    ldap: connector-ldap.yml
  groups:
    - directory_group: "All_SW_AdobeCC_Dynamic"
      adobe_groups:
        - User Group1

**Comment by Luci2015** [comment]
This error is potentially an UM API bug or a problem that is being forwarded as an error response from upstream services of the API, not a problem of the sync tool itself.

A workaround for this would be to choose a different policy than `remove-adobe-groups`, like plain `remove`, or just use `preserve` for adobe_only_user_action along with `--process-groups`, so that you keep your users inside the Users menu listing (if that's your intention) but strip away their entitlement, if that is given through the mapped groups.
`remove-adobe-groups` will remove all the group membership that an account is part of in Admin Console, indifferently if those groups are mapped or not (mentioned in the config file of UST).

**Comment by adorton-adobe** [comment]
I agree with @Luci2015 that you probably don't need `--remove-adobe-groups`.  `preserve` (the default) will ensure that Adobe-only users are removed from the groups they were added to using the sync tool.

I'd like to investigate this because it should be possible to remove a user from all groups.  Will you please email me at adorton@adobe.com with the following information?

* Organization name
* Organization ID
* Email address of user triggering this error
* Copy of a log file showing this error

**Comment by adorton-adobe** [comment]
Closing this due to age. Please re-open if the problem persists.
