### ISSUE TITLE
Add action summary to log

### ISSUE THREAD

**Issue by phil-levy** [adobe-apiplatform/user-sync.py#46]
Accumulate statistics and write them to the log file.  Including:

Number of directory users 
Number of Adobe users
Number of users created
Number of users updated
Number of users with updated groups
Number of users removed from mapped groups because they were not in directory
Number of users removed/deleted
Number of users with no changes

**Comment by ensembledeanw** [comment]
Dan commented in the [PR](https://github.com/adobe-apiplatform/user-sync.py/pull/103) for this issue to also include two more counts:
- number of directory users in the "selected" input set (i.e., filtered set)
- number of Adobe users that were "excluded from operations" (via the exclude_parameters)

**Comment by adobeDan** [comment]
Fixed with PR #108.

**Comment by adobeDan** [comment]
Reopening because there are some bugs in the impl.  Also the original request is confused: users can be removed from mapped groups without being strays.  And I don't believe there is any need to differentiate users that had attributes updated versus users that had group groups updated.  And we never do more than one kind of stray processing in a run.  So I believe the right statistics are:
- Directory users read
- Directory users in selected set
- Adobe users read
- Adobe users excluded
- Adobe users updated (attributes or groups)
- Adobe users processed as strays (removed/deleted/removed-entitlements or written to file)
- Adobe users with no changes
