### ISSUE TITLE
additional_groups not working in 2.4

### ISSUE THREAD

**Issue by cosmin-balanoiu** [adobe-apiplatform/user-sync.py#463]
[ust2.4additionalGroups.zip](https://github.com/adobe-apiplatform/user-sync.py/files/2956649/ust2.4additionalGroups.zip)

I tried every combination I could think of. I cannot get it to work.
I attached my config files and the last log. I tried this in 2.4 on python 3.6.5 and 3.6.6, in test mode and live, I always get the same result.
The AD group and the Admin Console one are named ADB-one.
 
The tool works fine if I comment out additional_groups.
 
Thanks,
Cosmin

**Comment by SCRICrtoole** [comment]
I am having similar issues.  The groups that match the RegEx do not sync, while those with explicit mappings do.  

I did have to single quote the expression because it did not like the "\1" in the target line.  That got it to run, but then I do not see the groups that match my expression.

Example
I changed

- source: "(.+)-ACL"
  #     target: "ACL-Grp-(\1)"

to 

- source: '(.+)-ACL'
  #     target: 'ACL-Grp-(\1)'

It's still not working, but there is definitely an issue with the examples as they are.

**Comment by cosmin-balanoiu** [comment]
any progress on this?

**Comment by vossen-adobe** [comment]
@cosmin-balanoiu can you give some examples of the full group names you are trying to match?

**Comment by cosmin-balanoiu** [comment]
Just "ADB-one". I tried to test this on a simple group to see if the tool picks it up after a report from a customer that this is not working. You can find the regexp I used in the attached files.

C

**Comment by vossen-adobe** [comment]
I get the same issues - I'll do some digging

**Comment by vossen-adobe** [comment]
Alright - two things: 

1) There seems to be a bug in the code where a string is passed instead of a list when only one group comes back for a user.  The method causing this is only called when there are additional groups mapped.  Unfortunately this means that everyone in your que must be in more than one group, even if they are not part of additional groups.   This should be likely be fixed in the next release.

2) Additional groups is targeting users who have groups in addition to being part of a normally mapped group.  In your case, only users who are in the group called "nested" will be pulled in by the additional groups method.  You can use --users all in if you needed to.  Neither of these will work correctly until the next version, however.

**Comment by vossen-adobe** [comment]
Near 309 in directory_ldap:

`    def get_member_groups(self, user):
        group_names = []
        groups = LDAPValueFormatter.get_attribute_value(user, 'memberOf')
        for group_dn in map(dn.str2dn, groups):
            group_cn = self.get_cn_from_dn(group_dn)
            if group_cn:
                group_names.append(group_cn)
        return group_names`

Should be changed to:

`       groups = LDAPValueFormatter.get_attribute_value(user, 'memberOf')
        if not groups:
            return group_names
        elif type(groups) is str:
        groups = [groups]`

**Comment by vossen-adobe** [comment]
https://github.com/adobe-apiplatform/user-sync.py/pull/472
