### ISSUE TITLE
log files do not automatically expire

### ISSUE THREAD

**Issue by wmadm90** [adobe-apiplatform/user-sync.py#485]
log files currently persist forever, which takes up needless disk space. it would be helpful if it was configurable to delete log files older than x days.

**Comment by adorton-adobe** [comment]
This is by design - the sync tool isn't responsible for log file cleanup.  There are many different use cases for how log files should be managed, so we decided it would be best to leave it up to the user to decide how they want to do it.

If you want a simple solution for linux or WSL (i.e. "Bash for Windows"), you can use `find` to clean up old files:

```
find logs/ -name \*.log -mtime +14 -delete
```

This example will delete any log file found in the "logs" directory older than 14 days.

**Comment by wmadm90** [comment]
i'm aware that there are ways to expire logs external from the application, and it appears that's the route i will go. i was directed by your own program manager to open a feedback item here for that feature request. i stand by my request that it would be useful for this functionality to exist within the application.

thanks,

walker
