### ISSUE TITLE
FederatedIDs not created if AdobeID exists

### ISSUE THREAD

**Issue by amorrowbellarmine** [adobe-apiplatform/user-sync.py#511]
I'm working on setting up user-sync for my University so users will be able log into CC2019 using federated credentials in computer labs. We've gone through the process of setting up our SSO and followed the instructions of configuring user-sync to import the users into Adobe's console. Everything looks to work except for one issue: If a user already has an AdobeID with the same email address, a FederatedID is not created. I don't know if the problem is with our configuration of user-sync or something in the Adobe API. 

I've looked through all the config options and previous issues for something similar to this problem. Issue #282 makes it sound like FederatedIDs would be created even if AdobeIDs exist in. Issue #84 sounds similar to my problem, but is closed due to lack of feedback from the creator.

Steps to reproduce:
I have an AdobeID user in the console with the email address "user@bellarmine.edu". If I run the command `python user-sync.pex --users all --user-filter user@bellarmine.edu` I see user-sync report `Creating user with user key: federatedID,user@bellarmine.edu,`. Turning up the logging to debug shows the umapi.action `Added action: {"user": "user@bellarmine.edu", "requestID": "action_1", "do": [{"createFederatedID": {"email": "user@bellarmine.edu", "option": "ignoreIfAlreadyExists", "firstname": "Ulysses", "lastname": "Ser", "country": "US"}}]}` and the HTTP response being 200. It appears user-sync is working correctly and determining it needs to create a federated user for "user@bellarmine.edu" and the API is accepting the POST command, but the end result is no FederatedID created.

I noticed another thing in the debug logs of user-sync while troubleshooting this. For FederatedID only users I see a log entry that says `Found Adobe-only user: federatedID,[removed]@bellarmine.edu`. For AdobeID only users I see a log entry that says `Excluding adobe user (due to type): adobeID,[removed]@bellarmine.edu`. There are 2 users in the console we've added manually that have both an AdobeID and FederatedID. For those users I only see the `Excluding adobe user (due to type): adobeID,[removed]@bellarmine.edu` log entry. I don't see the federatedID entry. That leads to another observation: I tried group mapping for a small set of users, some of which already had AdobeIDs shown in the console. During the group/user mapping phase user-sync added the AdobeID user to the Adobe group despite the fact I had that identity type excluded in the user-sync-config.yml file. It's as if the API or user-sync isn't able to distinguish an AdobeID from a FederatedID from one another if they have the same email address (or more likely, username).

Attached is the user-sync-config settings I'm using along with a sanitized debug log.

[user-sync-config.txt](https://github.com/adobe-apiplatform/user-sync.py/files/3407749/user-sync-config.txt)
[user-sync_debug_log.txt](https://github.com/adobe-apiplatform/user-sync.py/files/3407891/user-sync_debug_log.txt)

**Comment by adorton-adobe** [comment]
The UMAPI prevents Federated IDs from being created in cases where an Adobe ID exists in the console with the same email ID.  It will, however, assign the Adobe ID to its targeted groups.  This happens because when you update a user's group membership using the UMAPI, you can't explicitly tell it which identity type you'd like to target.  The UMAPI will prioritize Federated IDs above Adobe IDs, but since the Federated ID wasn't created, it will fall back to applying the group assignment to the Adobe ID.

This doesn't have anything to do with the AdobeID exclusion option.  That option just filters Adobe IDs from the list of Admin Console users queried by the sync tool.  It serves an important purpose by ensuring that Adobe IDs are never removed from the console or from target groups by the sync tool.

If you have a large number of users that already have Adobe IDs you'll want to look into migrating them to Federated before syncing them.  To migrate them, you change the identity type from Adobe ID to Federated ID.

https://helpx.adobe.com/enterprise/using/identity.html#EditIdentityType

And if they have assets stored in Creative or Document cloud, you'll need to plan to migrate their assets.

https://helpx.adobe.com/enterprise/using/identity.html#AssetMigration

If we're talking about a small number of users (especially if some or all are admins) you're probably better off manually creating Federated IDs for those users.  You can do that in the Admin Console UI.  The Admin Console allows you to create Federated users with the same email address as existing Adobe ID users despite the fact that the UMAPI doesn't allow it.

**Comment by amorrowbellarmine** [comment]
Okay, that makes sense. I just didn't find anything in the documentation for user-sync that indicated that FederatedIDs would not be created if AdobeIDs existed in the console. That's is part of why I was confused.
