### ISSUE TITLE
Feature Request: Multiple AD domains in same forest

### ISSUE THREAD

**Issue by XabiBeltza** [adobe-apiplatform/user-sync.py#524]
Hello.
It would be great if we could add more than on Active Directory domain for synchronization. This would allow us to do full sync, to remove unused users. Right now we use multiple scripts that only handle group and user info synchronization from users of each domain. If a user is disabled or stops being part of certaing groups, it is not managed and remains as it is.

It shouldn't be too difficult to implement. Basically allowing the configuration to have a list of ldap connectors. Then, each connector's output would be concatenated. After that, sync should work the same way as regularly.

Thanks!

**Comment by Luci2015** [comment]
Hi,
if your users can be discovered with the use of global catalog you can apply this:

--> add the global catalog port to the host
host: "ldap://your_domain_controller_name:3268"
--> make the base_dn to pick up an empty value:
base_dn: ""

have all your user groups inside the forrest, that require to be searched for members to be synced, to be Universal instead of Global.

This setup should require just one sync tool instance.

**Comment by XabiBeltza** [comment]
Thanks, it works!
It was really simple... Only downside is that it requires us to use
Universal groups

**Comment by adorton-adobe** [comment]
We may support multiple identity sources in a single sync process in the future.
