### ISSUE TITLE
Exclude specified domain users

### ISSUE THREAD

**Issue by AsakaOkuyama** [adobe-apiplatform/user-sync.py#543]
Hi experts, the customer tried to eliminate users who have a specified domain as below. He has some domains in the same AD security group, but there's only a domain he doesn't want to sync. So he configured his config files as below, but it seems the user synced.
file: user-sync-config.yml
```

parameta:
adobe_users:
exclude_users:
- ".*@ono-usa.com"
```

The result: INFO processor – Creating user with user key: federatedID,xxxx@ono-usa.com,

Is that an expected result? How can he config his file to exclude a specified domain?

**Comment by Luci2015** [comment]
That exclude_users statement refers to existing Adobe side, not LDAP side, therefore what you see is expected.

To exclude users from source one could alter the 'all_users_filter' so that particular users from specific location of the LDAP take part on the sync.
Here is a customized sample of what I mean (replace _@mydomain.com_ with the one domain to ignore from the _mail_ attribute; alternatively change the _mail_ attribute to some other attribute if that is what you set the tool to look for):
```
all_users_filter: "(&(objectClass=user)(objectCategory=person)(!(mail=*@mydomain.com))(!(userAccountControl:1.2.840.113556.1.4.803:=2)))"
```
There may be some other solutions, but I see this query is accepted in my default AD instance.

Please test and feedback.

**Comment by AsakaOkuyama** [comment]
Hi @Luci2015 , Thank you very much for teaching me. The customer succeeds in excluding the domain users. Thank you again.
