### ISSUE TITLE
About the number of LDAP requests to AD.

### ISSUE THREAD

**Issue by Tomomi99145** [adobe-apiplatform/user-sync.py#555]
Hi team,

Please tell me about the number of requests to AD.
Is there one request per a user?
If group mapping(--users mapped) is specified, is it request to only users added to the mapped group?

Regards,
Tomomi

**Comment by Tomomi99145** [comment]
Can someone answer to this question?

**Comment by Luci2015** [comment]
The tool would not send one request per user, rather an ldap query just as you'd use to extract same results directly in AD.

The "--users mapped" informs the tool to filter the AD users to be members* of the groups you named in the config file as "directory_group". These will be the only users that will get synced over to Admin Console.
* but not the ones that have it set as Primary Group, provided you do not mess with the default  group filters in the connector-ldap.yml file.

As a difference "--users all" will extract all the users from AD under the base_dn from the config file, based on the all_users_filter query.

**Comment by Tomomi99145** [comment]
Hi @Luci2015 
Thank you for your answer!!

Is the below correct?

・Use the "--users mapped"  will send ldap query for  the only mapped group users, will not send  for all the users from AD under the base_dn from the config file.

・ When setting nested group, Instead of following each nest one by one, will send ldap query to the only specified mapped group.

Regards,
Tomomi

**Comment by Luci2015** [comment]
Hi,
for q1:
The tool does an LDAP query **for each** group you named in the config file and it will be a logical AND between the `group_member_filter_format` and the `all_users_filter`:
* (&( (group_member_filter_format)(all_users_filter) )
* usually the group_member_filter_format is `(memberOf={group_dn})`. As you can see, the group_member_filter_format contains the `group_dn`, so that the results are restricted to be members of the mapped LDAP group, if you do not modify it to be something else. As consequence, you can extract the fact that the filtering is made LDAP side, not tool side, so the tool only obtains the filtered list of users that are members of that group, **not** the entire list of users from the base_dn.

for q2:
You are right, but this time the `group_member_filter_format ` will pick up this value instead (enabled from the connector-ldap.yml file):
`(memberOf:1.2.840.113556.1.4.1941:={group_dn})`
So if default queries from LDAP are used, the tool will send a query to the LDAP for each mapped group, that looks like:
`(&((memberOf:1.2.840.113556.1.4.1941:=**{group_dn}**)(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))))`,
where **group_dn** will be the one of the current queried group. 

The `memberOf:1.2.840.113556.1.4.1941` enables the nested group(s) lookup, therefore this is one LDAP query sent from the tool for the parent group.

If you want to take a look as well, please check the `load_users_and_groups` method ([here](https://github.com/adobe-apiplatform/user-sync.py/blob/v2/user_sync/connector/directory_ldap.py))
Also, I would not hardocode any of the group_dn values inside the connector-ldap file.

**Comment by Tomomi99145** [comment]
Hi @Luci2015 
Thank you for your kind answer!!
I understood well.

I hope that the new year is a good one for you.
Thank you!
Tomomi
