### ISSUE TITLE
Group of Adobe ID user changes even if excluded.

### ISSUE THREAD

**Issue by Tomomi99145** [adobe-apiplatform/user-sync.py#569]
Hi Team,
I have a question.

I registered Adobe ID on Admin Console.
I synced Federated ID to Admin Console using UST.
Adobe ID and Federated ID had the same email address.
At that time, Adobe ID was excluded by the config file.

Ran result is below;
　・Federated ID didn't create.
　・Adobe ID was added to user group(gourp mapped by UST) on Admin Console.

Why has Adobe ID was added user group despite excluding Adobe ID?

**Comment by adorton-adobe** [comment]
The UMAPI's behavior in this regard is inconsistent. When creating a Federated ID with the same email address as an existing Adobe ID, the federated ID is not created despite a "success" message from the API.

When updating a group membership for a user, there is no way to specify the identity type, so the UMAPI prioritizes Federated IDs over Adobe IDs. Since no Federated ID exists in this case, the Adobe ID is updated instead.

The best solution is to manually create the Federated ID in the admin console. The UST will then assign the group membership to the Federated account.

I'm closing this since this is a UMAPI issue and not a UST issue.
