### ISSUE TITLE
Add new addone administrator

### ISSUE THREAD

**Issue by vkuharkov** [adobe-apiplatform/user-sync.py#579]
Hello!
Is it possible to synchronize administrators in the adminconsole with this?

**Comment by Luci2015** [comment]
As long as they're not org admin type, you should be able to.  Read about the role naming convention [here](https://adobe-apiplatform.github.io/umapi-documentation/en/api/ActionsCmds.html), in the official UMAPI doc page.
The only admin type I would sync is the support admin for some of the users, because I don't see the gain in manually managing group/product memebership in Admin Console when you have a sync tool for this purpose.

**Comment by adorton-adobe** [comment]
Closing this since there have been no comments since March.
