### ISSUE TITLE
How to pecific OU (organization unit) be excluded from sync?

### ISSUE THREAD

**Issue by Tomomi99145** [adobe-apiplatform/user-sync.py#581]
Hi team,
Can I a specific OU (organization unit) be excluded from sync?

For example,
Sync target：base_dn: 'DC=daaan,DC=work'
Sync exclusion：'OU=disable,DC=daaan,DC=work'

Regards,
Tomomi

**Comment by vossenv** [comment]
You cant explicitly skip it - the ldap syntax for user filter isn't complex enough, but with users mapped it's easy to exclude users.  If using all users, you can use the extension config and change the email to something that will error, like 'skip'. It's not a great solution.  Better to use mapped users or narrow the out scope to just one

**Comment by Tomomi99145** [comment]
Hi @vossenv ,
Thank you for your answer!
What does ”narrow the out scope to just one” do?

**Comment by adorton-adobe** [comment]
Closing this since there have been no comments since March.

I'm also not sure this is an issue. I would need to know more about the LDAP system in this case, but in general, I don't think a user can belong to more than one OU, So as long as the users being synced don't come from the "disabled" OU you should be OK.
