### ISSUE TITLE
Product profile names don't match due to appended extra characters

### ISSUE THREAD

**Issue by nickila** [adobe-apiplatform/user-sync.py#645]
**Description**
Product profiles don't always match when they should due to additional characters being appended to the end of a product profile name in user groups in the umapi response. 

**Steps to reproduce**
* Relevant config options
* Command-line options used
* Specific details around identity source, group mapping, etc.

**Expected behavior**
product profile names should match even if one has a certain string of characters appended to the end if it matches a given regex.

**Screenshots**

**Environment**
 - UST version:
 - OS type and version:
 - Any other relevant info:

**Comment by adorton-adobe** [comment]
I'm reluctant to consider this a UST bug without investigating it more thoroughly. Based on the information in the linked PR, this relates to special profile groups that exist internally in JIL but aren't exposed in the Console UI. It is my understanding that they aren't supposed to be exposed by the UMAPI. The last time I spoke to the JIL team about it, they set the expectation that they would stop exposing these groups in a future release.

We should always be able to match the profile name verbatim (without respect to letter case). If we can't match a particular profile name, and we are sure that profile exists in the console, then that is an issue for the platform team to investigate. Any customer experiencing this should reach out to customer support.

Please email me the details on this - the Org Name, Org ID, a list of all of the groups returned by the UMAPI and the name of the profile the UST isn't finding. And please provide a screenshot showing that the profile is defined in the console UI.

**Comment by vossen-adobe** [comment]
I agree that this is not a ust bug - however, the reason for suggesting a patch is because this was a major blocker for some clients  and was preventing a lot of users from syncing.  However, the way around this is to not specify product profile name for entitling a user - and always use a user group instead.  The product mis-naming is extremely consistent and predictable and always looks something like this:

Default Creative Cloud_76TT88T-provisioning

Where the 76TT88T are random characters.  Here is a real example from a major client:

default adobe   sign-enterprise trns configuration_ae81b46-provisioning
default all apps - 1024 gb   configuration_ed79bff-provisioning
natural history museum acrobat pro   dc_28bb067-provisioning

I think this is a pretty common issue.  However, knowing we have a workaround (groups instead of entitlements), perhaps this fix is not necessary.  We will have the same thing happening in Phase II, however.

**Comment by adorton-adobe** [comment]
We'll need to bring this to the platform team.

**Comment by adorton-adobe** [comment]
I've sent them an email. For now, let's recommend that customers work around the issue with user groups, or if they are unwilling or unable to do that, submit a customer support ticket.

**Comment by adorton-adobe** [comment]
After some internal discussion, it looks like this change isn't necessary since `entitlement_groups` can specify more than one group (profile or user group) to define Sign entitlements for the connector.
