### ISSUE TITLE
LDAP connection failure: SSPI: InitializeSecurityContext: The specified target is unknown or unreachable

### ISSUE THREAD

**Issue by bajwa-adobe** [adobe-apiplatform/user-sync.py#654]
**Description**
Customer is setting up UST with AD. And used LDAPS with Kerberos authentication. 

It shows following error:
`LDAP connection failure: SSPI: InitializeSecurityContext: The specified target is unknown or unreachable`

**Steps to reproduce**
Set authentication_method to Kerberos and remove username and password fields and then run UST v2.6 in test-mode

* Relevant config options
`authentication_method: Kerberos`

* Command-line options used
` --process-groups --users mapped -t`

* Specific details around identity source, group mapping, etc.
`Federated ID`, One-to-one group mappings

**Expected behavior**
The LDAP connection should work. I tested the connection via `MS LDP.exe` and it worked all ok

**Screenshots**

**Environment**
 - UST version: v2.6.0
 - OS type and version: Windows
 - Any other relevant info:

**Comment by Luci2015** [comment]
have you tried to use as '''host''' address the FQDN of that particular server you tried the ldp.exe on? still same issue?

**Comment by bhunut-adobe** [comment]
With the current version of UST, you will need to specify Domain Controller FQDN instead of AD Domain name for Host.

When UST tried to authenticate using Kerberos,  it used the specified domain in the config file to authenticate. Since SPN doesn’t match with the domain controller, this causes the authentication to fail and throw this error.

I have the fix for this and it will require a new build of UST. Will push a PR after a few more testing. The fix will allow for Domain Name.
