### ISSUE TITLE
Transition from `uid` to `uid`@`domain.com`

### ISSUE THREAD

**Issue by n8felton** [adobe-apiplatform/user-sync.py#655]
Today, all of our users in the Admin Console are in the form of `uid`, however, the new IdP settings appear to be preferring `uid`@`domain.com` format.

Does this tool have the capability of transitioning all existing users in the Admin Console from the `uid` format to the `uid`@`domain.com` format?

**Comment by Luci2015** [comment]
I think you are refering to updating the Username's field value in Admin Console, right?
If that is the case, UST can't be ussed. If you cannot make the IdP to send the usual `uid` value you used to have before (which is the easiest out of this), you need to contact support to provide you with a secondary script to update the Username, then adapt the UST config to populate correctly both Email and Username fields in Admin Console for new accounts that get created after the switch.

**Comment by adorton-adobe** [comment]
@n8felton you should be able to do this in the Admin Console now. A feature was released very recently that allows username updates by CSV upload.

Just use the "Edit users by CSV" tool, download your users list, make the username updates, and upload the CSV.

I'm closing this since it should resolve your issue. If you experience any issues with the CSV tool, please open a support ticket from the Admin Console.
