### ISSUE TITLE
connector-ldap.yml not syncing sub-domain for user_domain_format

### ISSUE THREAD

**Issue by azizmoalim** [adobe-apiplatform/user-sync.py#666]
Hello,

I have a working 'connector-ldap.yml' file that uses the domain 'company.com'. Those users sync fine to Adobe and get licensed properly.

When I change that config file to use a sub-domain (sub.company.com), the domain is left blank in the Adobe Admin Console even though the 'connector-ldap.yml' reflects the 'sub.company.com' just fine. This causes a login failure since it's just the username with no domain when logging in.

**Has a domain using company.com:** 

2020-12-11 03:53:57 3948 INFO processor - Creating user with user key: federatedID,myusername,company.com

2020-12-11 22:53:57 3948 DEBUG umapi.action - Added action: {"user": "myusername", "domain": "company.com", "requestID": "action_1", "do": [{"createFederatedID": {"email": "myusername@company.com", "option": "ignoreIfAlreadyExists", "firstname": "MyName", "lastname": "MyLastName", "country": "US"}}, {"add": {"product": ["default all apps plan - 20 gb configuration"]}}]}

**Does not have a domain using sub.company.com:** 

2020-12-11 03:53:57 3948 INFO processor - Creating user with user key: federatedID,myusername,sub.company.com

2020-12-11 22:53:57 3948 DEBUG umapi.action - Added action: {"user": "myusername", "domain": "sub.company.com", "requestID": "action_1", "do": [{"createFederatedID": {"email": "myusername@sub.company.com", "option": "ignoreIfAlreadyExists", "firstname": "MyName", "lastname": "MyLastName", "country": "US"}}, {"add": {"product": ["default all apps plan - 20 gb configuration"]}}]}

Since we use Azure AD, the sub domain is required to match the Azure Account to the federated ID. How can I get the sync tool to add the sub domain instead of having to resort to manually editing?

Thank you.

**Comment by azizmoalim** [comment]
Update: It seems this isn't an issue related to the Adobe user sync tool. No matter how the accounts are created, manually in the Adobe Admin Center, a CSV import or the user sync tool, the sub domain is always missing. 

I've opened a case with Adobe. I'll update this page with Adobe's response later this week and close this issue.

**Comment by Luci2015** [comment]
so I take it that your federatedIDs are created in Admin Console with metadata such as ('myusername' below is not an email formatted value):
 - email: myusername@company.com
 - username: username
 - domain: company.com
and on top of those, you wish to create also accounts that have:
 - email: myusername@sub.company.com
 - username: username
 - domain: sub.company.com

If that is the case, you can try to let the tool extract the domain from the email address (or whatever attribute you set for user_email_format - could be mail, could be userPrincipalName) and not force one particular domain.
In this case, your filters could be set something like (no domain statement forced, using sAMAccountName as Username, but could be any attribute that matches your IdP setup to make your SSO work):
```
all_users_filter: "(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))"
group_filter_format: "(&(|(objectCategory=group)(objectClass=groupOfNames)(objectClass=posixGroup))(cn={group}))"
group_member_filter_format: "(memberOf={group_dn})"
user_email_format: "{mail}"
user_username_format: "{sAMAccountName}"
```

in this case, an account from LDAP with these attributes:
mail=myusername@company.com
sAMAccountName=myusername
will get created as usual with company.com domain

for a different user such as:
mail=myusername@sub.company.com
sAMAccountName=myusername
will get created with sub.company.com domain, since the tool picks up the domain from the email if 'domain' statement is missing.

Now it is all about targetting the right attributes: 
- is `sAMAccountName` a good attribute for that 'myusername' value? change it  accordidngly to what fits your LDAP
- is `mail` a good attribute to target both company.com and sub.company.com users? change to a different attribute that fits best all your users

For any change you do to user-sync, be sure to run a couple of times in test mode and verify if the run results are as expected.

**Comment by azizmoalim** [comment]
This has been resolved. 

The issue was caused by using the 'Username format' + 'Domain Format' options and if you were using the User Sync Wizard, it would be the 'Enable Username Format (for usernames based on login settings)'. Picture below.

For the 'Username Format', we were using {sAMAccountName} as the variable and 'sub.company.com' as the 'Domain Forest'. This would cause the domain to be missing completely in the usernames for a random amount of users when viewing them in the Adobe Admin Console Users list.

Even worst, since this sub organization utilized a trusted directory, we assumed the issue was isolated to this sub organization. We were wrong. The issue caused from the user sync tool impacted the main organization's directory and removed the domain for those users as well. Now the user was missing the domain in their username in the sub and main organization directories.

After some trial and error, we stopped using 'Username format' + 'Domain Format', deleted the users completely from both directories and ran the user sync tool again. The problem was now gone and the users sync'd as expected, domain and all.

Picture: https://i.imgur.com/RrQ0ze2.png
