### ISSUE TITLE
Can't get removed AD users to deprovision in Adobe

### ISSUE THREAD

**Issue by azizmoalim** [adobe-apiplatform/user-sync.py#670]
Hello,

While searching online on how to remove federated users from Adobe who are missing from our local AD, I stumbled across this option from version 1.1.1 of the user sync tool, it appears that this option was later removed in updated versions.

'--remove-nonexistent-users'
Explanation thanks to [jamesg123](https://github.com/adobe-apiplatform/user-sync.py/issues/9#issuecomment-278899297):

> parser.add_argument('--remove-nonexistent-users',
                    help='Causes the user sync tool to remove Federated users that exist on the Adobe side if they are not in the customer side AD. This has the effect of deleting the user account if that account is owned by the organization under which the sync operation is being run.',
                    action='store_true', dest='remove_nonexistent_users')

Initial question from a user: [https://github.com/adobe-apiplatform/user-sync.py/issues/9](https://github.com/adobe-apiplatform/user-sync.py/issues/9)

Adobe releases a new version to solve it: Release notes of v1.1.1 [https://github.com/adobe-apiplatform/user-sync.py/releases/tag/v1.1.1-with-docs](https://github.com/adobe-apiplatform/user-sync.py/releases/tag/v1.1.1-with-docs)

Is this feature gone? During my testing, when I remove a federated user from the local AD group that the Adobe user sync tool uses, the user continues exists in the Adobe side. This feature would solve this issue by removing federated users in the Adobe side who are no longer in the sync'd AD group.

Thanks,
Aziz

**Comment by adorton-adobe** [comment]
This option was replaced by the `--adobe-only-user-action` option (and the `adobe_only_user_action` invocation option) in the 2.x release cycle. 

This setting supports a variety of options for handling Adobe-only users (users found in UMAPI queries but not LDAP queries).

* `exclude` - don't take any action
* `preserve` - if `--process-groups` is enabled, then remove user from targeted groups, otherwise do nothing
* `remove-adobe-groups` - remove all Adobe groups, even those not targeted in group mapping
* `remove` - remove user from organization, but not underlying directory
* `delete` - fully delete user from underlying directory, which will remove user from any directory trustee orgs and will also delete users' cloud storage
* `write-file` (requires additional filename param) - take no action but write Adobe-only users to a file

The default is `preserve` which explains why you are still seeing the accounts. The `remove` option will probably do what you want, but be very careful with that option and make sure you run the sync in test mode to make sure it doesn't remove more users than intended. I recommend setting the `adobe_users` option to `mapped` if you want to remove Adobe-only users.

**Comment by azizmoalim** [comment]
Thanks @adorton-adobe, that was it! I guess I got caught up with the terms Adobe ID and Adobe-Only.
