### ISSUE TITLE
About the "RuntimeWarning" displayed when running UST 2.6.5

### ISSUE THREAD

**Issue by takasead** [adobe-apiplatform/user-sync.py#741]
**Description**
I ran UST2.6.5.
On the DOS window, I got the following "Warning" message.
Is there any way to avoid this display?

**Steps to reproduce**
The command that was executed
user-sync.exe -t --adobe-users mapped --adobe-only-user-action remove

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/70120450/137043034-c3f97432-71af-41e7-8b85-c6129b4bfe79.png)
**Environment**
 - UST version:
User Sync version: 2.6.5
 - OS type and version:
Windows Server 2019 Datacenter
 - Any other relevant info
The log after execution is attached.
[log.txt](https://github.com/adobe-apiplatform/user-sync.py/files/7333680/log.txt)
:

**Comment by adorton-adobe** [comment]
Python has always ignored buffering in binary mode, but didn't report any warnings until Python 3.8. See https://bugs.python.org/issue32236

As of UST 2.6.5, we build with Python 3.9, which is why this warning now appears. It isn't something for any user to be concerned about. I'll fix this for the next release.
