### ISSUE TITLE
Additional_groups not working with Okta connector

### ISSUE THREAD

**Issue by pierresteiner** [adobe-apiplatform/user-sync.py#762]
**Description**
When Okta is used as a connector additional_groups: https://github.com/adobe-apiplatform/user-sync.py/blob/b9ef4d5f26280ddbfc356da5bc130669fadc92f5/examples/config%20files%20-%20basic/user-sync-config.yml#L194 are not working. Problem is caused by this line: https://github.com/adobe-apiplatform/user-sync.py/blob/a2df5ef427b32f19d9e412c9863292e24d361959/user_sync/app.py#L375 it expects dynamic_group_member_attribute to be defined, but it is not relevant to the Okta connector

**Steps to reproduce**
* Configure okta as a connector
* Enable additional_groups

**Expected behavior**
Dynamic group mapping should work with Okta as well

**Screenshots**

**Environment**
 - UST version: 2.7.0

**Comment by adorton-adobe** [comment]
Unfortunately, due to the nature of the Okta APIs, we can't support this for the Okta connector. The API doesn't provide a list of all groups associated with a user profile. When we query users we must do so by group.

I did fix the error you get with the missing `dynamic_group_member_attribute` setting. Now if you try to use the `additional_groups` feature with the Okta connector you get an warning that it isn't supported.
