### ISSUE TITLE
SSL error starting with 2.6.2 version

### ISSUE THREAD

**Issue by madumro** [adobe-apiplatform/user-sync.py#779]
**Description**
On the same Windows server, the most recent UST versions fail with:
"CRITICAL main - Connection to org <org_id> at endpoint https://usermanagement.adobe.io/v2/usermanagement failed: HTTPSConnectionPool(host='ims-na1.adobelogin.com', port=443): Max retries exceeded with url: /ims/exchange/jwt (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))"

**Steps to reproduce**
UST 2.6.0 works properly, but when upgrading to UST 2.7.0 or 2.7.3, some costumers get SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))
No change is done inside the configuration files or on the server.

**Expected behavior**
The upgrade should be possible.

**Environment**
 - UST version: 2.6.2 and above
 - OS type and version: Windows

**Comment by adorton-adobe** [comment]
In my experience, when you see an SSL error there's generally an issue with the network environment. It's not uncommon for corporate networks to inspect outgoing SSL traffic. In order to that, they decrypt SSL traffic and then re-encrypt it for transit outside the network. If the application performing this brokering work doesn't have updated CA certs or doesn't implement SSL correctly, it can lead to problems with client applications like the UST.

My best guess is that the crypto libraries in the UST were upgraded in one of the recent releases and the proxy has issues handling the SSL traffic the UST is now sending it. There's nothing we can do with the UST unfortunately. We can't roll back dependencies that are critical to maintaining security.

The best solution is to raise the issue with the organization's network security to see if there's anything they can do. In the meantime, SSL verification can be disabled by setting `ssl_verify` to `False` in the UMAPI connector config.

**Comment by adorton-adobe** [comment]
I'm going to close this since there isn't anything to fix on the UST.

**Comment by madumro** [comment]
Thank you for your answer!

**Comment by Luci2015** [comment]
In case someone else is looking for a solution, we found that a problem generating this issue is the existance of an environment variable (`HTTPS_PROXY`) set for a proxy address using a **wrong** protocol.
For example, if the proxy operates in reality on `http` but the HTTPS_PROXY env vaiable was created using `https` protocol for the proxy, like this:
`HTTPS_PROXY=https://your.proxy.address:port`
then this makes a likely scenario to obtain the `'EOF occurred in violation of protocol` error.

A fix for the above is to change the protocol on the environment variable to `http` like this:
`HTTPS_PROXY=http://your.proxy.address:port`

Note, that environment variables might be set at runtime (inside the batch/shell/ps script that starts the UST) and are only valid for that run, but these can also be set system wide as a global/local OS setting for environment variables. So check both locations to see if a change is required in any of these locations.
