### ISSUE TITLE
users not processed correctly when username and email have different domains

### ISSUE THREAD

**Issue by cbalanoiu** [adobe-apiplatform/user-sync.py#808]
**Description**
Users are not processed correctly when username and email have different domains when removing from file.

**Steps to reproduce**
When using write-to-file the tool exports [type,username,domain]
When removing from file (--adobe-only-user-list users-to-delete.csv --adobe-only-user-action delete) the username value is compared to the email

**Expected behavior**
The tool should compare corresponding values , i.e. have a case for username and email with different domains.

**Screenshots**
<img width="828" alt="Screenshot 2022-12-05 at 14 10 10" src="https://user-images.githubusercontent.com/15031997/205644348-3cd7adc7-a40f-4221-99d2-5fdbcd2ef740.png">
<img width="638" alt="Screenshot 2022-12-05 at 14 13 36" src="https://user-images.githubusercontent.com/15031997/205644365-7368c000-84be-40b5-98be-1af6df71c382.png">

**Environment**
 - UST version: 2.7.5
 - OS type and version: Win Server 2012

**Comment by adorton-adobe** [comment]
The central issue is that the UMAPI expects the user to be identified by email address and not username.

I've resolved this issue by modifying the write function to write the email address of each user instead of the username. The read function has been modified to look for the email address first and only try the username if the email address is not provided. This maintains backward compatibility.

It now logs a warning if the username is being used to identify a user.

See https://github.com/adobe-apiplatform/user-sync.py/commit/651d2117150d59030276297867eeef2d6c09093b for more info.
