### ISSUE TITLE
Unhandled exception in logs-accounts not being uploaded to Adobe

### ISSUE THREAD

**Issue by blackholemac** [adobe-apiplatform/user-sync.py#854]
Specific problem is the following. Before this, it does attempt to parse the many AD users we are trying to sync up to the Adobe Admin console. I'm willing to post my three .yml files, BUT I am concerned about publishing credentials on a Github forum. Same applies to the logs, given that they contain information about my company's domain. Please advise what info you need and how I can provide it to you in a way that is helpful and secure. Also note, I receive the same errors when using version 2.9.1 (the fully supported one). I simply tried the beta hoping that it might fix something weird.

2024-06-19 11:50:56 4436 CRITICAL main - Unhandled exception
Traceback (most recent call last):
  File "user_sync\app.py", line 461, in run_sync
  File "user_sync\app.py", line 409, in begin_work_umapi
  File "user_sync\engine\umapi.py", line 198, in run
  File "user_sync\engine\umapi.py", line 509, in sync_umapi_users
  File "user_sync\engine\umapi.py", line 823, in create_umapi_user
  File "user_sync\engine\umapi.py", line 844, in get_from_index
ValueError: too many values to unpack (expected 4)
2024-06-19 11:50:56 4436 INFO main - ========== End Run (User Sync version: 2.10.0rc2) (Total time: 0:00:06)

**Comment by blackholemac** [comment]
Attached is a sanitized version of the .yml files
[Archive.zip](https://github.com/user-attachments/files/15903636/Archive.zip)

**Comment by adorton-adobe** [comment]
The sync tool appears to be getting unexpected data from the identity source. Will you please email a log file to adorton AT adobe.com? I'd like to review the logs to see if I can pinpoint the issue

**Comment by blackholemac** [comment]
Those were submitted earlier today. Thank you for reviewing things and I appreciate any help. Unhandled exceptions i know usually are not good.

**Comment by adorton-adobe** [comment]
Thank you for sending those items. I don't have enough information to know for sure what is happening, but my guess is there is an email address in your identity system that contains a comma. Internally the UST keeps track of users with a composite identifier consisting of identity type, email address, username and domain. These items are encoded in a comma-delimited string. This is considered safe to do because commas are not valid characters in email addresses, usernames or domain names. But the error indicates there's an extra comma in some user field (presumably the email address since you do not map a different username field).

I'll add a check for this condition that will report the user key causing the error.

**Comment by adorton-adobe** [comment]
Since I haven't heard from you recently, I'm closing this issue.
