### ISSUE TITLE
Complete work on account removal

### ISSUE THREAD

**Issue by phil-levy** [adobe-apiplatform/user-sync.py#90]
In particular, --remove-entitlements-for-nonexistent-users

**Comment by adobeDan** [comment]
OK, so I am not going to add yet another list option for this kind of removal, instead I am going to make all the list options use the name `orphan` rather than `remove` or `delete` so that we just have one set of list options that apply to all three remove/delete options.  That will make the usage instructions a lot clearer as well.

**Comment by adobeDan** [comment]
Damn!  `--remove-entitlements-for-orphans` sounds really bad.  I might have to stick with `--remove-entitlements-for-orphan-users`.  Going to look for a better word in the thesaurus.  Hmmmm.  How about `stray-users` or `strays`.  That works better.

**Comment by phil-levy** [comment]
I haven't followed the discussion,  but DO NOT use the term orphan in any names.  Please use the name we speced  remove entitlements for nonexistent users.  Hold release if this needs more discussion.



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by phil-levy** [comment]
Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by adobeDan** [comment]
No worries, @phil-levy, we won't release with new names (and none of the proposed names involve orphans :).  We can discuss next week.

**Comment by adobeDan** [comment]
Finally settled on using "unmatched" instead of "nonexistent" externally, and "strays" instead of "orphans" internal to the code.
